#!/bin/bash

#################################
#  viernes, 10 de marzo de 2016  #
#################################
#
#
#
#
#-------------------------------------------------------------------------------
# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS: 
# Lista los path de los ficheros actualmente seleccionados.
# Devolvería un path como: "/home/user/Mi PDF.pdf".
#
# NAUTILUS_SCRIPT_SELECTED_URIS:
# Lista de URIs de los ficheros delimitadas por \n (URI=Universal Resource Indicator).
# Devolvería varias URI como: "file:///home/user/Mi%20PDF.pdf".
#
# NAUTILUS_SCRIPT_CURRENT_URI:
# Actual URI del fichero selecionado..
# Devolvería una URI como: "file:///home/user/Mi%20PDF.pdf".
#
# NAUTILUS_SCRIPT_WINDOW_GEOMETRY:
# Tamaño y localización de la ventana.
# Devolveria una cadena al estilo: 1000×800+10+50
# Indica dimensiones hor. y vert.de la ventana y su posicion x, y.
#-------------------------------------------------------------------------------
progress_bar() {
    zenity --progress --pulsate --auto-close --no-cancel --width 400 --text="$1"
}

if [ ! -f "/usr/bin/convert" ];then
    zenity --error --title="Error: convert no se encuentra instalado" \
        --text="\"sudo apt-get install imagemagick\"" \
        --no-wrap
    exit 1
elif [ ! -f "/usr/bin/pdfunite" ];then
    zenity --error --title="Error: pdfunite no se encuentra instalado" \
        --text="\"sudo apt-get install poppler-utils\"" \
        --no-wrap
    exit 1
fi

DIR=$(pwd)
WORKDIR=$(mktemp -d)

NAME=$(zenity --entry --text="Introduce el nombre del archivo pdf")
NAME=${NAME:=output}
NAME="$NAME.pdf"

if [ -f "$NAME" ];then
    zenity --error --text="\"$NAME\" ya existe" --no-wrap
    exit 1
fi

ONEPDF="pdfunite"

for path in ${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS// /%20}
do
    IMG2PDF="convert -compress jpeg -quality 95 -resize 1654x2340 -gravity center -extent 1654x2340 -units PixelsPerInch -density 200x200"
    
    file=${path##*/}
    file=${file//\%20/ }
    
    type=$(file --mime-type "$file"| awk -F\/ '{print $NF}')

    if [[ "$type" == "png" || "$type" == "jpeg" ]];then
        out="$WORKDIR/${file%.*}-merged.pdf"
        
        IMG2PDF="$IMG2PDF ${file// /\\ } ${out// /\\ }"
        ONEPDF="$ONEPDF ${out// /\\ }"

        ${IMG2PDF}
    else
        zenity --error --text="Error:\n\"$file\" no es una imagen" --no-wrap
        exit 1
    fi
done > >(progress_bar ">>> \"$NAME\"")
ONEPDF="$ONEPDF $WORKDIR/out.pdf"

${ONEPDF}| progress_bar "$NAME"
mv "$WORKDIR/out.pdf" "$NAME"

rm -r "$WORKDIR"
rmdir "$WORKDIR"

zenity --info --text="Trabajo terminado" --no-wrap
exit 0
